// Supabase Database Types
export interface Database {
  public: {
    Tables: {
      EstateProperties: {
        Row: {
          Id: string;
          StreetName: string | null;
          HouseNumber: string | null;
          Neighborhood: string | null;
          City: string | null;
          State: string | null;
          ZipCode: string | null;
          Country: string | null;
          LocationLatitude: number;
          LocationLongitude: number;
          Title: string;
          Type: number;
          AreaValue: number;
          AreaUnit: number;
          Bedrooms: number;
          Bathrooms: number;
          HasGarage: boolean;
          GarageSpaces: number;
          Visits: number | null;
          MainImageId: string | null;
          OwnerId: string | null;
          IsDeleted: boolean;
          Created: string;
          CreatedBy: string | null;
          LastModified: string;
          LastModifiedBy: string | null;
          MinStayDays: number | null;
          MaxStayDays: number | null;
          LeadTimeDays: number | null;
          BufferDays: number | null;
        };
        Insert: {
          Id?: string;
          StreetName?: string | null;
          HouseNumber?: string | null;
          Neighborhood?: string | null;
          City?: string | null;
          State?: string | null;
          ZipCode?: string | null;
          Country?: string | null;
          LocationLatitude: number;
          LocationLongitude: number;
          Title: string;
          Type: number;
          AreaValue: number;
          AreaUnit: number;
          Bedrooms: number;
          Bathrooms: number;
          HasGarage: boolean;
          GarageSpaces: number;
          Visits?: number | null;
          MainImageId?: string | null;
          OwnerId?: string | null;
          IsDeleted?: boolean;
          Created?: string;
          CreatedBy?: string | null;
          LastModified?: string;
          LastModifiedBy?: string | null;
          MinStayDays?: number | null;
          MaxStayDays?: number | null;
          LeadTimeDays?: number | null;
          BufferDays?: number | null;
        };
        Update: {
          Id?: string;
          StreetName?: string | null;
          HouseNumber?: string | null;
          Neighborhood?: string | null;
          City?: string | null;
          State?: string | null;
          ZipCode?: string | null;
          Country?: string | null;
          LocationLatitude?: number;
          LocationLongitude?: number;
          Title?: string;
          Type?: number;
          AreaValue?: number;
          AreaUnit?: number;
          Bedrooms?: number;
          Bathrooms?: number;
          HasGarage?: boolean;
          GarageSpaces?: number;
          Visits?: number | null;
          MainImageId?: string | null;
          OwnerId?: string | null;
          IsDeleted?: boolean;
          Created?: string;
          CreatedBy?: string | null;
          LastModified?: string;
          LastModifiedBy?: string | null;
          MinStayDays?: number | null;
          MaxStayDays?: number | null;
          LeadTimeDays?: number | null;
          BufferDays?: number | null;
        };
      };
      EstatePropertyValues: {
        Row: {
          Id: string;
          Description: string | null;
          AvailableFrom: string;
          Capacity: number | null;
          Currency: number;
          SalePrice: number | null;
          RentPrice: number | null;
          HasCommonExpenses: boolean;
          CommonExpensesValue: number | null;
          IsElectricityIncluded: boolean | null;
          IsWaterIncluded: boolean | null;
          IsPriceVisible: boolean;
          Status: number;
          IsActive: boolean;
          IsPropertyVisible: boolean;
          IsFeatured: boolean;
          EstatePropertyId: string;
          IsDeleted: boolean;
          Created: string;
          CreatedBy: string | null;
          LastModified: string;
          LastModifiedBy: string | null;
        };
        Insert: {
          Id?: string;
          Description?: string | null;
          AvailableFrom: string;
          Capacity?: number | null;
          Currency?: number;
          SalePrice?: number | null;
          RentPrice?: number | null;
          HasCommonExpenses?: boolean;
          CommonExpensesValue?: number | null;
          IsElectricityIncluded?: boolean | null;
          IsWaterIncluded?: boolean | null;
          IsPriceVisible?: boolean;
          Status?: number;
          IsActive?: boolean;
          IsPropertyVisible?: boolean;
          IsFeatured?: boolean;
          EstatePropertyId: string;
          IsDeleted?: boolean;
          Created?: string;
          CreatedBy?: string | null;
          LastModified?: string;
          LastModifiedBy?: string | null;
        };
        Update: {
          Id?: string;
          Description?: string | null;
          AvailableFrom?: string;
          Capacity?: number | null;
          Currency?: number;
          SalePrice?: number | null;
          RentPrice?: number | null;
          HasCommonExpenses?: boolean;
          CommonExpensesValue?: number | null;
          IsElectricityIncluded?: boolean | null;
          IsWaterIncluded?: boolean | null;
          IsPriceVisible?: boolean;
          Status?: number;
          IsActive?: boolean;
          IsPropertyVisible?: boolean;
          IsFeatured?: boolean;
          EstatePropertyId?: string;
          IsDeleted?: boolean;
          Created?: string;
          CreatedBy?: string | null;
          LastModified?: string;
          LastModifiedBy?: string | null;
        };
      };
      Members: {
        Row: {
          Id: string;
          UserId: string;
          FirstName: string | null;
          LastName: string | null;
          Title: string | null;
          AvatarUrl: string | null;
          Street: string | null;
          Street2: string | null;
          City: string | null;
          State: string | null;
          PostalCode: string | null;
          Country: string | null;
          MemberSubscriptionId: string | null;
          IsDeleted: boolean;
          Created: string;
          CreatedBy: string | null;
          LastModified: string;
          LastModifiedBy: string | null;
          Phone: string | null;
          Role: string | null;
          Email: string | null;
          TwoFactorEnabled: boolean;
        };
        Insert: {
          Id?: string;
          UserId: string;
          FirstName?: string | null;
          LastName?: string | null;
          Title?: string | null;
          AvatarUrl?: string | null;
          Street?: string | null;
          Street2?: string | null;
          City?: string | null;
          State?: string | null;
          PostalCode?: string | null;
          Country?: string | null;
          MemberSubscriptionId?: string | null;
          IsDeleted?: boolean;
          Created?: string;
          CreatedBy?: string | null;
          LastModified?: string;
          LastModifiedBy?: string | null;
          Phone?: string | null;
          Role?: string | null;
          Email?: string | null;
          TwoFactorEnabled?: boolean;
        };
        Update: {
          Id?: string;
          UserId?: string;
          FirstName?: string | null;
          LastName?: string | null;
          Title?: string | null;
          AvatarUrl?: string | null;
          Street?: string | null;
          Street2?: string | null;
          City?: string | null;
          State?: string | null;
          PostalCode?: string | null;
          Country?: string | null;
          MemberSubscriptionId?: string | null;
          IsDeleted?: boolean;
          Created?: string;
          CreatedBy?: string | null;
          LastModified?: string;
          LastModifiedBy?: string | null;
          Phone?: string | null;
          Role?: string | null;
          Email?: string | null;
          TwoFactorEnabled?: boolean;
        };
      };
      EstatePropertyAmenity: {
        Row: {
          EstatePropertyId: string;
          AmenityId: string;
          CreatedAtUtc: string;
          DeletedAtUtc: string | null;
        };
        Insert: {
          EstatePropertyId: string;
          AmenityId: string;
          CreatedAtUtc?: string;
          DeletedAtUtc?: string | null;
        };
        Update: {
          EstatePropertyId?: string;
          AmenityId?: string;
          CreatedAtUtc?: string;
          DeletedAtUtc?: string | null;
        };
      };
      Amenities: {
        Row: {
          Id: string;
          Name: string;
          IconName: string | null;
          IsDeleted: boolean;
          Created: string;
          CreatedBy: string | null;
          LastModified: string;
          LastModifiedBy: string | null;
        };
        Insert: {
          Id?: string;
          Name: string;
          IconName?: string | null;
          IsDeleted?: boolean;
          Created?: string;
          CreatedBy?: string | null;
          LastModified?: string;
          LastModifiedBy?: string | null;
        };
        Update: {
          Id?: string;
          Name?: string;
          IconName?: string | null;
          IsDeleted?: boolean;
          Created?: string;
          CreatedBy?: string | null;
          LastModified?: string;
          LastModifiedBy?: string | null;
        };
      };
      CalendarIntegrations: {
        Row: {
          Id: string;
          EstatePropertyId: string;
          PlatformType: number;
          ExternalCalendarId: string;
          ExternalCalendarName: string | null;
          AccessToken: string | null;
          RefreshToken: string | null;
          TokenExpiresAt: string | null;
          IsActive: boolean;
          LastSyncAt: string | null;
          SyncStatus: number;
          IsDeleted: boolean;
          Created: string;
          CreatedBy: string | null;
          LastModified: string;
          LastModifiedBy: string | null;
          ICalUrl: string | null;
          ICalSyncToken: string | null;
        };
        Insert: {
          Id?: string;
          EstatePropertyId: string;
          PlatformType: number;
          ExternalCalendarId: string;
          ExternalCalendarName?: string | null;
          AccessToken?: string | null;
          RefreshToken?: string | null;
          TokenExpiresAt?: string | null;
          IsActive?: boolean;
          LastSyncAt?: string | null;
          SyncStatus?: number;
          IsDeleted?: boolean;
          Created?: string;
          CreatedBy?: string | null;
          LastModified?: string;
          LastModifiedBy?: string | null;
          ICalUrl?: string | null;
          ICalSyncToken?: string | null;
        };
        Update: {
          Id?: string;
          EstatePropertyId?: string;
          PlatformType?: number;
          ExternalCalendarId?: string;
          ExternalCalendarName?: string | null;
          AccessToken?: string | null;
          RefreshToken?: string | null;
          TokenExpiresAt?: string | null;
          IsActive?: boolean;
          LastSyncAt?: string | null;
          SyncStatus?: number;
          IsDeleted?: boolean;
          Created?: string;
          CreatedBy?: string | null;
          LastModified?: string;
          LastModifiedBy?: string | null;
          ICalUrl?: string | null;
          ICalSyncToken?: string | null;
        };
      };
    };
  };
}
